//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redis.Cache.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas varius, orci d" +
            "ictum semper dignissim, sapien velit gravida sapien, nec pharetra libero tellus " +
            "ac elit. Nullam luctus leo sit amet metus interdum, non volutpat urna malesuada." +
            " Sed posuere, neque vel laoreet rutrum, purus massa cursus neque, id sodales nib" +
            "h enim non arcu. Sed nibh dui, semper eu tempus non, interdum id elit. Quisque o" +
            "rnare lorem quis sodales dapibus. Donec ullamcorper augue ut turpis volutpat pel" +
            "lentesque. Nulla ornare pulvinar dolor, quis auctor nunc feugiat vitae. Aliquam " +
            "tincidunt, nulla ut luctus venenatis, massa magna vehicula lectus, a eleifend an" +
            "te arcu vel mauris. Fusce in massa at mauris porttitor placerat ac nec elit.\r\n\r\n" +
            "Vestibulum fringilla metus vel mi porta, molestie vehicula purus commodo. Nam in" +
            " lectus at risus ullamcorper adipiscing ac et quam. Vivamus non sagittis diam, n" +
            "on blandit eros. Integer consectetur pharetra massa sit amet facilisis. Suspendi" +
            "sse ornare velit porta nisi tempor, eget faucibus lorem cursus. Pellentesque con" +
            "gue ante quis tellus pellentesque, et adipiscing lorem adipiscing. Pellentesque " +
            "habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas." +
            " Fusce malesuada nulla ligula, id placerat urna placerat eu.\r\n\r\nMauris tincidunt" +
            " orci a nibh auctor, nec lobortis dolor porta. Ut interdum dignissim orci, vel d" +
            "ictum felis sollicitudin ac. Nam a lacinia purus. Cras non arcu in augue iaculis" +
            " consequat eget quis felis. In ut fringilla justo, a accumsan urna. Suspendisse " +
            "auctor dui volutpat metus hendrerit imperdiet. Vestibulum quis nisl ac enim ultr" +
            "ices tristique non sit amet velit. Curabitur dignissim sit amet risus a pellente" +
            "sque. Phasellus quis pellentesque metus. Integer sit amet lacus est. Cras fringi" +
            "lla ipsum ut magna eleifend, quis ornare nunc semper. Quisque nec enim at odio c" +
            "ongue venenatis. Praesent porta nunc gravida adipiscing ullamcorper. Vestibulum " +
            "in orci non nisi congue rhoncus eget sit amet est. Curabitur urna turpis, semper" +
            " vitae posuere eu, feugiat vitae risus. Fusce scelerisque, dolor ut tempus posue" +
            "re, nunc risus elementum sem, in porttitor turpis metus nec est. ")]
        public string Value_Text {
            get {
                return ((string)(this["Value_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas varius, orci d" +
            "ictum semper dignissim, sapien velit gravida sapien, nec pharetra libero tellus " +
            "ac elit. Nullam luctus leo sit amet metus interdum, non volutpat urna malesuada." +
            "")]
        public string Value_Text_small {
            get {
                return ((string)(this["Value_Text_small"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<START>\r\nTest 0987654321 メンズア\r\n\r\nLorem ipsum dolor sit amet, consectetur adipisci" +
            "ng elit. Maecenas varius, orci dictum semper dignissim, sapien velit gravida sap" +
            "ien, nec pharetra libero tellus ac elit. Nullam luctus leo sit amet metus interd" +
            "um, non volutpat urna malesuada. Sed posuere, neque vel laoreet rutrum, purus ma" +
            "ssa cursus neque, id sodales nibh enim non arcu. Sed nibh dui, semper eu tempus " +
            "non, interdum id elit. Quisque ornare lorem quis sodales dapibus. Donec ullamcor" +
            "per augue ut turpis volutpat pellentesque. Nulla ornare pulvinar dolor, quis auc" +
            "tor nunc feugiat vitae. Aliquam tincidunt, nulla ut luctus venenatis, massa magn" +
            "a vehicula lectus, a eleifend ante arcu vel mauris. Fusce in massa at mauris por" +
            "ttitor placerat ac nec elit.\r\n\r\nVestibulum fringilla metus vel mi porta, molesti" +
            "e vehicula purus commodo. Nam in lectus at risus ullamcorper adipiscing ac et qu" +
            "am. Vivamus non sagittis diam, non blandit eros. Integer consectetur pharetra ma" +
            "ssa sit amet facilisis. Suspendisse ornare velit porta nisi tempor, eget faucibu" +
            "s lorem cursus. Pellentesque congue ante quis tellus pellentesque, et adipiscing" +
            " lorem adipiscing. Pellentesque habitant morbi tristique senectus et netus et ma" +
            "lesuada fames ac turpis egestas. Fusce malesuada nulla ligula, id placerat urna " +
            "placerat eu.\r\n\r\nMauris tincidunt orci a nibh auctor, nec lobortis dolor porta. U" +
            "t interdum dignissim orci, vel dictum felis sollicitudin ac. Nam a lacinia purus" +
            ". Cras non arcu in augue iaculis consequat eget quis felis. In ut fringilla just" +
            "o, a accumsan urna. Suspendisse auctor dui volutpat metus hendrerit imperdiet. V" +
            "estibulum quis nisl ac enim ultrices tristique non sit amet velit. Curabitur dig" +
            "nissim sit amet risus a pellentesque. Phasellus quis pellentesque metus. Integer" +
            " sit amet lacus est. Cras fringilla ipsum ut magna eleifend, quis ornare nunc se" +
            "mper. Quisque nec enim at odio congue venenatis. Praesent porta nunc gravida adi" +
            "piscing ullamcorper. Vestibulum in orci non nisi congue rhoncus eget sit amet es" +
            "t. Curabitur urna turpis, semper vitae posuere eu, feugiat vitae risus. Fusce sc" +
            "elerisque, dolor ut tempus posuere, nunc risus elementum sem, in porttitor turpi" +
            "s metus nec est. \r\n\r\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. M" +
            "aecenas varius, orci dictum semper dignissim, sapien velit gravida sapien, nec p" +
            "haretra libero tellus ac elit. Nullam luctus leo sit amet metus interdum, non vo" +
            "lutpat urna malesuada. Sed posuere, neque vel laoreet rutrum, purus massa cursus" +
            " neque, id sodales nibh enim non arcu. Sed nibh dui, semper eu tempus non, inter" +
            "dum id elit. Quisque ornare lorem quis sodales dapibus. Donec ullamcorper augue " +
            "ut turpis volutpat pellentesque. Nulla ornare pulvinar dolor, quis auctor nunc f" +
            "eugiat vitae. Aliquam tincidunt, nulla ut luctus venenatis, massa magna vehicula" +
            " lectus, a eleifend ante arcu vel mauris. Fusce in massa at mauris porttitor pla" +
            "cerat ac nec elit.\r\n\r\nVestibulum fringilla metus vel mi porta, molestie vehicula" +
            " purus commodo. Nam in lectus at risus ullamcorper adipiscing ac et quam. Vivamu" +
            "s non sagittis diam, non blandit eros. Integer consectetur pharetra massa sit am" +
            "et facilisis. Suspendisse ornare velit porta nisi tempor, eget faucibus lorem cu" +
            "rsus. Pellentesque congue ante quis tellus pellentesque, et adipiscing lorem adi" +
            "piscing. Pellentesque habitant morbi tristique senectus et netus et malesuada fa" +
            "mes ac turpis egestas. Fusce malesuada nulla ligula, id placerat urna placerat e" +
            "u.\r\n\r\nMauris tincidunt orci a nibh auctor, nec lobortis dolor porta. Ut interdum" +
            " dignissim orci, vel dictum felis sollicitudin ac. Nam a lacinia purus. Cras non" +
            " arcu in augue iaculis consequat eget quis felis. In ut fringilla justo, a accum" +
            "san urna. Suspendisse auctor dui volutpat metus hendrerit imperdiet. Vestibulum " +
            "quis nisl ac enim ultrices tristique non sit amet velit. Curabitur dignissim sit" +
            " amet risus a pellentesque. Phasellus quis pellentesque metus. Integer sit amet " +
            "lacus est. Cras fringilla ipsum ut magna eleifend, quis ornare nunc semper. Quis" +
            "que nec enim at odio congue venenatis. Praesent porta nunc gravida adipiscing ul" +
            "lamcorper. Vestibulum in orci non nisi congue rhoncus eget sit amet est. Curabit" +
            "ur urna turpis, semper vitae posuere eu, feugiat vitae risus. Fusce scelerisque," +
            " dolor ut tempus posuere, nunc risus elementum sem, in porttitor turpis metus ne" +
            "c est. \r\n\r\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas va" +
            "rius, orci dictum semper dignissim, sapien velit gravida sapien, nec pharetra li" +
            "bero tellus ac elit. Nullam luctus leo sit amet metus interdum, non volutpat urn" +
            "a malesuada. Sed posuere, neque vel laoreet rutrum, purus massa cursus neque, id" +
            " sodales nibh enim non arcu. Sed nibh dui, semper eu tempus non, interdum id eli" +
            "t. Quisque ornare lorem quis sodales dapibus. Donec ullamcorper augue ut turpis " +
            "volutpat pellentesque. Nulla ornare pulvinar dolor, quis auctor nunc feugiat vit" +
            "ae. Aliquam tincidunt, nulla ut luctus venenatis, massa magna vehicula lectus, a" +
            " eleifend ante arcu vel mauris. Fusce in massa at mauris porttitor placerat ac n" +
            "ec elit.\r\n\r\nVestibulum fringilla metus vel mi porta, molestie vehicula purus com" +
            "modo. Nam in lectus at risus ullamcorper adipiscing ac et quam. Vivamus non sagi" +
            "ttis diam, non blandit eros. Integer consectetur pharetra massa sit amet facilis" +
            "is. Suspendisse ornare velit porta nisi tempor, eget faucibus lorem cursus. Pell" +
            "entesque congue ante quis tellus pellentesque, et adipiscing lorem adipiscing. P" +
            "ellentesque habitant morbi tristique senectus et netus et malesuada fames ac tur" +
            "pis egestas. Fusce malesuada nulla ligula, id placerat urna placerat eu.\r\n\r\nMaur" +
            "is tincidunt orci a nibh auctor, nec lobortis dolor porta. Ut interdum dignissim" +
            " orci, vel dictum felis sollicitudin ac. Nam a lacinia purus. Cras non arcu in a" +
            "ugue iaculis consequat eget quis felis. In ut fringilla justo, a accumsan urna. " +
            "Suspendisse auctor dui volutpat metus hendrerit imperdiet. Vestibulum quis nisl " +
            "ac enim ultrices tristique non sit amet velit. Curabitur dignissim sit amet risu" +
            "s a pellentesque. Phasellus quis pellentesque metus. Integer sit amet lacus est." +
            " Cras fringilla ipsum ut magna eleifend, quis ornare nunc semper. Quisque nec en" +
            "im at odio congue venenatis. Praesent porta nunc gravida adipiscing ullamcorper." +
            " Vestibulum in orci non nisi congue rhoncus eget sit amet est. Curabitur urna tu" +
            "rpis, semper vitae posuere eu, feugiat vitae risus. Fusce scelerisque, dolor ut " +
            "tempus posuere, nunc risus elementum sem, in porttitor turpis metus nec est. \r\n\r" +
            "\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas varius, orci" +
            " dictum semper dignissim, sapien velit gravida sapien, nec pharetra libero tellu" +
            "s ac elit. Nullam luctus leo sit amet metus interdum, non volutpat urna malesuad" +
            "a. Sed posuere, neque vel laoreet rutrum, purus massa cursus neque, id sodales n" +
            "ibh enim non arcu. Sed nibh dui, semper eu tempus non, interdum id elit. Quisque" +
            " ornare lorem quis sodales dapibus. Donec ullamcorper augue ut turpis volutpat p" +
            "ellentesque. Nulla ornare pulvinar dolor, quis auctor nunc feugiat vitae. Aliqua" +
            "m tincidunt, nulla ut luctus venenatis, massa magna vehicula lectus, a eleifend " +
            "ante arcu vel mauris. Fusce in massa at mauris porttitor placerat ac nec elit.\r\n" +
            "\r\nVestibulum fringilla metus vel mi porta, molestie vehicula purus commodo. Nam " +
            "in lectus at risus ullamcorper adipiscing ac et quam. Vivamus non sagittis diam," +
            " non blandit eros. Integer consectetur pharetra massa sit amet facilisis. Suspen" +
            "disse ornare velit porta nisi tempor, eget faucibus lorem cursus. Pellentesque c" +
            "ongue ante quis tellus pellentesque, et adipiscing lorem adipiscing. Pellentesqu" +
            "e habitant morbi tristique senectus et netus et malesuada fames ac turpis egesta" +
            "s. Fusce malesuada nulla ligula, id placerat urna placerat eu.\r\n\r\nMauris tincidu" +
            "nt orci a nibh auctor, nec lobortis dolor porta. Ut interdum dignissim orci, vel" +
            " dictum felis sollicitudin ac. Nam a lacinia purus. Cras non arcu in augue iacul" +
            "is consequat eget quis felis. In ut fringilla justo, a accumsan urna. Suspendiss" +
            "e auctor dui volutpat metus hendrerit imperdiet. Vestibulum quis nisl ac enim ul" +
            "trices tristique non sit amet velit. Curabitur dignissim sit amet risus a pellen" +
            "tesque. Phasellus quis pellentesque metus. Integer sit amet lacus est. Cras frin" +
            "gilla ipsum ut magna eleifend, quis ornare nunc semper. Quisque nec enim at odio" +
            " congue venenatis. Praesent porta nunc gravida adipiscing ullamcorper. Vestibulu" +
            "m in orci non nisi congue rhoncus eget sit amet est. Curabitur urna turpis, semp" +
            "er vitae posuere eu, feugiat vitae risus. Fusce scelerisque, dolor ut tempus pos" +
            "uere, nunc risus elementum sem, in porttitor turpis metus nec est. \r\n\r\n Lorem ip" +
            "sum dolor sit amet, consectetur adipiscing elit. Maecenas varius, orci dictum se" +
            "mper dignissim, sapien velit gravida sapien, nec pharetra libero tellus ac elit." +
            " Nullam luctus leo sit amet metus interdum, non volutpat urna malesuada. Sed pos" +
            "uere, neque vel laoreet rutrum, purus massa cursus neque, id sodales nibh enim n" +
            "on arcu. Sed nibh dui, semper eu tempus non, interdum id elit. Quisque ornare lo" +
            "rem quis sodales dapibus. Donec ullamcorper augue ut turpis volutpat pellentesqu" +
            "e. Nulla ornare pulvinar dolor, quis auctor nunc feugiat vitae. Aliquam tincidun" +
            "t, nulla ut luctus venenatis, massa magna vehicula lectus, a eleifend ante arcu " +
            "vel mauris. Fusce in massa at mauris porttitor placerat ac nec elit.\r\n\r\nVestibul" +
            "um fringilla metus vel mi porta, molestie vehicula purus commodo. Nam in lectus " +
            "at risus ullamcorper adipiscing ac et quam. Vivamus non sagittis diam, non bland" +
            "it eros. Integer consectetur pharetra massa sit amet facilisis. Suspendisse orna" +
            "re velit porta nisi tempor, eget faucibus lorem cursus. Pellentesque congue ante" +
            " quis tellus pellentesque, et adipiscing lorem adipiscing. Pellentesque habitant" +
            " morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce m" +
            "alesuada nulla ligula, id placerat urna placerat eu.\r\n\r\nMauris tincidunt orci a " +
            "nibh auctor, nec lobortis dolor porta. Ut interdum dignissim orci, vel dictum fe" +
            "lis sollicitudin ac. Nam a lacinia purus. Cras non arcu in augue iaculis consequ" +
            "at eget quis felis. In ut fringilla justo, a accumsan urna. Suspendisse auctor d" +
            "ui volutpat metus hendrerit imperdiet. Vestibulum quis nisl ac enim ultrices tri" +
            "stique non sit amet velit. Curabitur dignissim sit amet risus a pellentesque. Ph" +
            "asellus quis pellentesque metus. Integer sit amet lacus est. Cras fringilla ipsu" +
            "m ut magna eleifend, quis ornare nunc semper. Quisque nec enim at odio congue ve" +
            "nenatis. Praesent porta nunc gravida adipiscing ullamcorper. Vestibulum in orci " +
            "non nisi congue rhoncus eget sit amet est. Curabitur urna turpis, semper vitae p" +
            "osuere eu, feugiat vitae risus. Fusce scelerisque, dolor ut tempus posuere, nunc" +
            " risus elementum sem, in porttitor turpis metus nec est.\r\n\r\nTest 0987654321 メンズア" +
            "\r\n<END>\r\n")]
        public string Value_Text_long {
            get {
                return ((string)(this["Value_Text_long"]));
            }
            set {
                this["Value_Text_long"] = value;
            }
        }
    }
}
