//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redis.Cache.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas varius, orci d" +
            "ictum semper dignissim, sapien velit gravida sapien, nec pharetra libero tellus " +
            "ac elit. Nullam luctus leo sit amet metus interdum, non volutpat urna malesuada." +
            " Sed posuere, neque vel laoreet rutrum, purus massa cursus neque, id sodales nib" +
            "h enim non arcu. Sed nibh dui, semper eu tempus non, interdum id elit. Quisque o" +
            "rnare lorem quis sodales dapibus. Donec ullamcorper augue ut turpis volutpat pel" +
            "lentesque. Nulla ornare pulvinar dolor, quis auctor nunc feugiat vitae. Aliquam " +
            "tincidunt, nulla ut luctus venenatis, massa magna vehicula lectus, a eleifend an" +
            "te arcu vel mauris. Fusce in massa at mauris porttitor placerat ac nec elit.\r\n\r\n" +
            "Vestibulum fringilla metus vel mi porta, molestie vehicula purus commodo. Nam in" +
            " lectus at risus ullamcorper adipiscing ac et quam. Vivamus non sagittis diam, n" +
            "on blandit eros. Integer consectetur pharetra massa sit amet facilisis. Suspendi" +
            "sse ornare velit porta nisi tempor, eget faucibus lorem cursus. Pellentesque con" +
            "gue ante quis tellus pellentesque, et adipiscing lorem adipiscing. Pellentesque " +
            "habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas." +
            " Fusce malesuada nulla ligula, id placerat urna placerat eu.\r\n\r\nMauris tincidunt" +
            " orci a nibh auctor, nec lobortis dolor porta. Ut interdum dignissim orci, vel d" +
            "ictum felis sollicitudin ac. Nam a lacinia purus. Cras non arcu in augue iaculis" +
            " consequat eget quis felis. In ut fringilla justo, a accumsan urna. Suspendisse " +
            "auctor dui volutpat metus hendrerit imperdiet. Vestibulum quis nisl ac enim ultr" +
            "ices tristique non sit amet velit. Curabitur dignissim sit amet risus a pellente" +
            "sque. Phasellus quis pellentesque metus. Integer sit amet lacus est. Cras fringi" +
            "lla ipsum ut magna eleifend, quis ornare nunc semper. Quisque nec enim at odio c" +
            "ongue venenatis. Praesent porta nunc gravida adipiscing ullamcorper. Vestibulum " +
            "in orci non nisi congue rhoncus eget sit amet est. Curabitur urna turpis, semper" +
            " vitae posuere eu, feugiat vitae risus. Fusce scelerisque, dolor ut tempus posue" +
            "re, nunc risus elementum sem, in porttitor turpis metus nec est. ")]
        public string Value_Text {
            get {
                return ((string)(this["Value_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas varius, orci d" +
            "ictum semper dignissim, sapien velit gravida sapien, nec pharetra libero tellus " +
            "ac elit. Nullam luctus leo sit amet metus interdum, non volutpat urna malesuada." +
            "")]
        public string Value_Text_small {
            get {
                return ((string)(this["Value_Text_small"]));
            }
        }
    }
}
